### ISSUE TITLE
Incorrect code for PFFile to NSImage conversion in OS X guide

### ISSUE THREAD

**Issue by tkrajacic** [ParsePlatform/Docs#198]
The OS X developers guide shows the following code (in section _Files > Images_)

```
PFFile *userImageFile = anotherPhoto[@"imageFile"];
[userImageFile getDataInBackgroundWithBlock:^(NSData *imageData, NSError *error) {
    if (!error) {
        UIImage *image = [UIImage imageWithData:imageData];
    }
}];
```
for creating an image from PFFile data. This is clearly a copy from the iOS guide as it is using __UIImage__ instead of __NSImage__ and therefore wrong.

The code for creating an __NSImage__ is not so trivial, as there is no simple PNGRepresentation method on NSImage and you need to take retina scaling into account when creating an image from NSData.

**Comment by nlutsenko** [comment]
This sounds about right... 
I think the problem comes down to a fact that the code for both platforms is cross-platform, and not split per iOS/OSX.
I am slightly rusty on OS X AppKit, but as far as I can see - `[[NSImage alloc] initWithData:imageData]` should already unblock people from doing other things, like up/down scaling for drawing.

Would love to hear your thoughts and review any Pull Request to make this documentation better.

**Comment by tkrajacic** [comment]
I have to admit I was stupid and forgot to quote the actual problematic part:

````
let imageData = UIImagePNGRepresentation(image)
let imageFile = PFFile(name:"image.png", data:imageData)
````

As you noted, the re-constructing from data is easy, but the creation of the png data is not.
Both code samples are incorrect though.
