### ISSUE TITLE
Cloud Code Modules API Reference Missing

### ISSUE THREAD

**Issue by Simone-cogno** [ParsePlatform/Docs#209]
The links to the API reference for Cloud code modules don't work anymore (On the JavaScript documentation). Ex "Stripe", "Apps Links".
Then i didn't found any reference of the cloud modules in the API reference page of the javascript SDK.

**Comment by abremner** [comment]
+1 I really need to access the full API reference docs for the Stripe Cloud Module. This page has been 404 for a few days now. https://parse.com/docs/js/api/classes/Stripe.html

**Comment by moesalih** [comment]
:+1:

**Comment by emkman** [comment]
Same, I need Stripe docs. It is really frustrating to try to use simple methods from the Stripe docs and find out they are not available in the Cloud Code version. In my case, I need to add a card to an existing customer. According to Stripe docs, I should be calling
```javascript
stripe.customers.createSource({CUSTOMER_ID}, {
  source: {TOKEN_ID}
});
````
but according to the mirror which @abremner has kindly provided, I need to call
```javascript
Stripe.Customers.update({CUSTOMER_ID}, {
  card: {TOKEN_ID} 
});
```
Different method name and different parameter name. I would have no way of knowing this without the docs, and we have no access to the module source.

Either maintain an up to date version of the module, **with docs**, or remove it entirely and tell people to use the REST api. This in-between is confusing, unacceptable, and frankly worse than nothing.

**Comment by emkman** [comment]
After my last post, I implemented the Parse `Stripe.Customers.update` only to find that it only supports replacing a default card, and cannot add a second card to a customer. Therefore, I had to fallback using the REST API, further underscoring my previous comment. The Stripe Cloud Code module in it's current state isn't good for much more than a basic demo.

**Comment by andrewimm** [comment]
@emkman, at this point we don't recommend using cloud modules, because as you noticed they're outdated versions. Your best bet is to include the modules you need directly in your "cloud" folder, that way you can use modern versions and control the versioning yourself.

However, we will get right on fixing the broken doc links.

**Comment by emkman** [comment]
@andrewimm Thanks for the reply. I already do maintain a "vendor" folder within my "cloud" folder to do what you suggest with other third party libraries. Is it possible to access the source of the cloud code modules? This way I could evaluate the code and decide if I want to extract certain parts into my own source tree. Thanks.

**Comment by hramos** [comment]
@emkman we have no plans to provide the source for any of the built-in Cloud Code Modules at this time. Each Module has remained unchanged since their original release. I would like to echo Andrew, I strongly advise anyone interested in using the Stripe, Twilio, Mandrill, etc modules to use the up to date JavaScript library maintained by each of these providers instead of the deprecated Cloud Code Modules.

**Comment by emkman** [comment]
@hramos Andrew's point was very clear. The problem is that nowhere in the docs do you state that the Cloud Modules are deprecated: https://www.parse.com/docs/cloudcode/guide#cloud-code-modules

Further, in some cases the documented behavior is incorrect or incomplete. I would just reiterate that in their current state they do more harm than good, and if you aren't going to open source them, you should truly deprecate them and remove them from the current guide. 

They can still run for people already using them, but people going to start a new implementation of any of these services are walking into a trap. You say that "you strongly advise" the use of provider's libraries, but where is that stated outside of this thread?

**Comment by llaski** [comment]
@emkman How do you make requests to the Stripe REST API, like which package do you use? The `http` module is almost completely stripped and without npm there isn't any way to pull in the typically request libraries that are out there.

Really need npm to be available in Parse, it would remove the need to maintain any sort of stripped down module which apparently isn't the case anyways since they are deprecated (never would have known without stumbling on this thread) and it makes Parse much more difficult to work with not being able to use npm.

**Comment by emkman** [comment]
@llaski I don't use the node `http` module if that is what you meant. I use `Parse.Cloud.httpRequest` and then follow the REST docs from Stripe. Here is an example:

```
var chargeUrl = "https://" + stripeSecretKey + "@api.stripe.com/v1/charges";
return Parse.Cloud.httpRequest({
  url: chargeUrl,
  method: "POST",
  body: {
    currency: "usd",
    amount: totalInCents,
    description: receiptDescription,
    statement_descriptor: statementDescriptor,
    customer: customerId,
    source: cardId
  }
}).then(function(httpResponse) {
    var charge = httpResponse.data;
    ...
}, function(error) {
    ...
});
```

Notice that I am doing Basic Authentication over HTTPS via the URL. Alternatively you could pass your key via the headers, but they are functionally equivalent and both are supported by Stripe. Also, you don't need to set the `Content-Type` explicitly but note that Stripe only supports `application/x-www-form-urlencoded`, not `application/json`. You can set this explicitly for clarity:
```
return Parse.Cloud.httpRequest({
  url: accountUrl,
  method: "POST",
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded'
  },
  body: {
    "legal_entity[type]": "individual",
    ...
```
This also means that nested parameters must be sent as shown in the example above using square brackets. You unfortunately **cannot** use objects to send something like:
```
body: {
  legal_entity: {
    type: "individial",
    ...
  }
}
```

On a more broad note, we are currently in the process of transitioning to our own hosting as described at http://blog.parse.com/learn/using-node-js-with-parse/. This way we can actually use a full Node and NPM environment, plus some other goodies like babel, local debugging, and websockets. The reality is that vendoring 3rd party clients into your cloud folder just isn't practical because they usually have too many dependencies. I once rewrote the entire official AWS S3 client + HMAC authentication so it would work vendored on Parse without dependencies. It wasn't fun.

I hope that helps.

**Comment by hramos** [comment]
@emkman agree that the wording here can be improved -- we plan to address this shortly. As a short term fix, I recently updated the Cloud Modules documentation to note that developers seeking the most up to date JavaScript libraries should import those directly as opposed to using the built-in Cloud Modules (see #273).

**Comment by hramos** [comment]
@llaski while Cloud Code and Node.js are both built on top of the V8 JavaScript engine, they're not the same thing. If you're interested in using Node.js, you can use webhooks to redirect a Cloud Function to Node.js running on a server of your choice (such as a Heroku instance under your control). The blog post referred to by @emkman is a good reference to get started: http://blog.parse.com/learn/using-node-js-with-parse/

**Comment by llaski** [comment]
@emkman That's incredibly helpful!! I did not notice `Parse.Cloud.httpRequest` and really thought there was no way to make requests to the outside world...Thank you so much!

I also agree with moving it to an outside hosting environment and then connecting with parse via its package. Without npm trying to import modules directly and store them in a folder like you describe is definitely a nightmare.  Some you can't even do with parse like Stripe because they use native node modules like `child_process` for example and it's not like you can just find that package on npm, its part of the native node environment which doesn't exist in parse. Unfortunately for the project I'm on not able to move it to a separate server at the moment.

Can't believe you rewrote a full AWS client, crazy stuff!

**Comment by lrettig** [comment]
Hi guys

As a new Parse user--and one who seriously considered Heroku, GAE and a number of other options for a new project, and went out on a limb a chose Parse as an experiment--I have encountered a number of frustrations and challenges, but I want to state very clearly that the issues discussed in this thread are by far the biggest, and make me want to seriously reconsider my choice of Parse as a platform.

I chose Parse to save time and make app development faster and easier. I'm writing an app that integrates fairly heavily with Stripe. I was already feeling frustrated that I can't use the full Stripe npm module in my frontend code because `http` is missing (and it's not really running on node, as I understand). Finding out that I can't run it on the backend either, that I have to jump through the hoops described above to get it working, and, to make matters worse, that the documentation on this topic is woefully out of date (I didn't notice this thread for days while I spun cycles on this project, and only found it after an hour of searching today) is sort of the final straw for me.

You're doing a lot of things right with Parse and there are a lot of fantastic things about the service, but it's time to fully embrace node and the open ecosystem of thousands of amazing modules. The integration with Heroku is a big step in the right direction. But documentation which is misleading and out of date (and clearly has been now for many months) is sort of unforgivable, from my perspective, for a platform that purports to make app development faster and easier as its raison d'etre.

I hope you'll understand that my criticism is intended in a constructive manner and I hope it's helpful. I think Parse is getting very close to becoming a platform that serious, experienced developers consider for enterprise scale projects, but without complete, accurate documentation and access to modern modules, I don't know how that can realistically happen.

Thanks!

**Comment by hramos** [comment]
@lrettig thanks for sharing your feedback. We'll make sure all of this information is clearly reflected in the docs. Have you tried using `Parse.Cloud.httpRequest` in place of `http`? That's the documented way of making network calls in Cloud Code.

**Comment by lrettig** [comment]
Hi @hramos 

Appreciate the response! I just want to use an existing module. And as far as I know, the Stripe npm module relies on `http`. If there's a version that uses `Parse.Cloud.httpRequest` instead, I'd love to take a look at it.

Thanks.

**Comment by hramos** [comment]
Any JavaScript code that is added to your Parse Cloud Code environment will need to use `Parse.Cloud.httpRequest` to make network calls. If you're adapting a Node module for use in Cloud Code, you will need to make these changes to the module's source. This is not specific to the Stripe module.

**Comment by lrettig** [comment]
Gotcha, that makes sense. As I said, I'm just trying to use existing modules--unfortunately I don't have the resources to modify existing modules to work with Parse. I chose Parse in the first place to save time :) For now it seems the only option is to downgrade the Parse JS SDK and use the old cloud version of Stripe until there's a better option.

**Comment by emkman** [comment]
@lrettig I may be wrong but I don't think downgrading the Parse SDK is necessary. The limited Cloud Code version of the Stripe module still exists in the current SDK as far as I know, and if so, it will have the same functionality as previous versions. The functionality has remained fixed and isn't upgraded, but it hasn't been downgraded/removed either.

**Comment by hramos** [comment]
Cloud Code Modules, as in the ones provided as part of Cloud Code and not via your `cloud/` folder, are not linked to any Parse SDK version, as they are a part of Cloud Code. This is why you cannot simply get a newer Cloud Code Module by updating the Parse SDK used in Cloud Code. Cloud Code does not support versioned Cloud Code Modules and we cannot update the modules in place without possibly breaking apps that depend on those specific initial versions. This is why we recommend adding your own JavaScript files to the `cloud/` folder where you have full control of the code that is released on your deploy, and you are free to use any version of the vendor's JavaScript library as needed.

**Comment by lrettig** [comment]
When I tried to use the Stripe cloud code module with the latest version of the Parse SDK, I got errors. After downgrading, it worked.

Anyway, I ended up moving my backend to Heroku and using the real Stripe module in npm and it's working great. Thanks for the help.
