### ISSUE TITLE
To Do Android tutorial does not work with current Android SDK

### ISSUE THREAD

**Issue by megaritzmom** [ParsePlatform/Docs#276]
In my Android class at Tulsa Community College, we are required to do your To Do tutorial and make the app work. Your tutorial is incomplete and has many problem areas. (I have been a programmer for over 10 years, and I have a couple of years experience with iOS, and I took the Android class a couple of years ago when they used Eclipse.) Even when I downloaded the code using the zip version, I am hitting exactly the same kinds of problems, but at least the member variables are there, which they are not in the tutorial. I have managed to create a workaround for almost everything, but the biggest problem is that the tutorial uses a class called ParseQueryAdapter, which apparently no longer exists in your current Android SDK. What am I supposed to use instead of that? I can't use the download available on Git because it is not set up for Android Studio. I tried importing it, but ran into all kinds of problems doing that.

**Comment by grantland** [comment]
Hrmm, unfortunately it looks like this tutorial is a bit outdated, thanks for bringing this to our attention! `ParseQueryAdapter` has since been moved from the core SDK to [`ParseUI-Android`](https://github.com/ParsePlatform/ParseUI-Android) which I can try helping you workaround until the sample project gets updated.

For now, could you clarify that you're trying to use this project ([OfflineTodos](https://github.com/ParsePlatform/OfflineTodos)) and whether you're using Eclipse or Android Studio?

If you're using Android Studio, you can add `ParseUI-Android` to your `build.gradle` dependencies:

```java
dependencies {
    ...
    compile 'com.parse:parseui-widget-android:0.0.1'
}
```

Unfortunately if you're using Eclipse, there's no way to use the maven repository and we no longer publish a JAR, but you can add the `ParseQueryAdapter.java` source file to your project manually from [here](https://github.com/ParsePlatform/ParseUI-Android/blob/master/ParseUI-Widget/src/main/java/com/parse/ParseQueryAdapter.java).

Hopefully this is enough to help you complete your assignment!
