### ISSUE TITLE
How to update my Object?

### ISSUE THREAD

**Issue by ryanemax** [ParsePlatform/Docs#364]
It failed when I use the example:

``` js
// Create the object.
var GameScore = Parse.Object.extend("GameScore");
var gameScore = new GameScore();

gameScore.set("score", 1337);
gameScore.set("playerName", "Sean Plott");
gameScore.set("cheatMode", false);
gameScore.set("skills", ["pwnage", "flying"]);

gameScore.save(null, {
  success: function(gameScore) {
    // Now let's update it with some new data. In this case, only cheatMode and score
    // will get sent to the cloud. playerName hasn't changed.
    gameScore.set("cheatMode", true);
    gameScore.set("score", 1338);
    gameScore.save();
  }
});
```

Error

``` sh
error: Error generating response. ParseError { code: 206, message: 'Cannot modify user Ihe5BFU9gr.' } code=206, message=Cannot modify user Ihe5BFU9gr. ParseUser { _objCount: 1, className: '_User', id: 'Ihe5BFU9gr' }  
```

**Comment by ryanemax** [comment]
When I use object.save(), it just go error, never access success

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the docs for Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
