### ISSUE TITLE
Project needs to be updated for local development

### ISSUE THREAD

**Issue by OmgImAlexis** [ParsePlatform/Docs#367]
Currently when you install the docs it redirects to the github page's domain even if you're in development mode.

```
➜  ~ curl  http://localhost:4000/docs/ 
<!DOCTYPE html>
<meta charset="utf-8">
<title>Redirecting…</title>
<link rel="canonical" href="https://parseplatform.github.io/#sdks">
<meta http-equiv="refresh" content="0; url=https://parseplatform.github.io/#sdks">
<h1>Redirecting…</h1>
<a href="https://parseplatform.github.io/#sdks">Click here if you are not redirected.</a>
<script>location="https://parseplatform.github.io/#sdks"</script>
```

**Comment by hramos** [comment]
This was bugging me as well. The redirect was in place because we were lacking an index page for the docs site. I've added it in 486cee62dee422b0bb45eca5f1380a76c7ee9e30.

You can check it out at http://parseplatform.github.io/docs (if it still redirects, go to http://parseplatform.github.io/docs/index.html directly. It seems like GH Pages takes a bit longer to update the redirection rules).
