### ISSUE TITLE
Resend email confirmation endpoint not documented

### ISSUE THREAD

**Issue by majidhassan** [ParsePlatform/Docs#433]
Starting 2.3.7 an endpoint for resending the email confirmation has been added. I can't seem to find any documentation for that one. I looked [here](http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.User.html). Does it exist somewhere else?

**Comment by flovilmart** [comment]
The REST endpoint has been added as is not documented. The client SDK's haven't been updated yet for this endpoint.

**Comment by natario1** [comment]
@flovilmart is there a list of endpoints/features yet to be implemented by client SDKs? Should we maintain one? It would be great if when new features are added to parse-server, an issue is opened to each client repo.

**Comment by flovilmart** [comment]
@natario1 yes, at one point we'll need to make sure we'll on par with the client SDK'S do you wanna take the lead on that?

**Comment by natario1** [comment]
@flovilmart I can be helpful three weeks from now. What's the plan? Do we want to automate this in Github, like, automatically opening issues in client repos?

**Comment by flovilmart** [comment]
I dunno how we can automate that, perhaps a project on parse-server with tasks on it, and it would create an issue for each repo through a bot? 🤔

**Comment by natario1** [comment]
I have no experience with bots or projects, but yeah, something like that. Setting up a parse bot would be cool! Though we need a community server running it afaik?

**Comment by addisonElliott** [comment]
So I have been giving some thought to the best way to create an automated script to add features. With all the issues/pull-requests on Parse Server page, it would be difficult for the bot to determine when pull requests require new features for the documentation.

Here is my idea:

Create a webpage with a text input form (on Github pages possibly) that the user can write one issue that will be submitted to each of the repositories. The page could have a checkbox list where the user selects which repositories this issue should be repeated 
- The benefit of this is that no separate Github account is required since there is no 'bot' but rather you just use your own Github account.
- Also, no community server is required since you can host the script using Github pages.
- Sounds like less work than having to program a bot to determine when to add issues to docs pages. 
- A bad thing to this idea is that the user must know to use this script. It would need to be documented how to use it.
- Script could be abused to spam adding issues. Although, this seems to be a minor problem

If we want to go this route, I may have some time the next few weeks to implement it. It shouldn't be **too*  difficult (isn't that what we always think?) to code in Javascript.

**Comment by TomWFox** [comment]
I think it makes sense to close this now as although there are some great ideas in here there has been no recent interest and it's rather off topic for this repo.

If anyone is still interested in this perhaps open a topic on the new [community forum](https://community.parseplatform.org).
